### ISSUE TITLE
Lifecycle Events...Use Returned Object Outside Callback...?

### ISSUE THREAD

**Issue by sirvon** [JoanZapata/android-asyncservice#12]
How to handle lifecycle events in the activities/fragments where the objects are returned?

In my analytics service I'm creating a mixpanel instance and returning it to the calling activity.

How do I use that object in OnResume or OnPause?

Or pretty much how do I use that object outside of the callback....

I'm having a issue understanding how to use the returned object outside on the @OnMessage
callback.....

**Comment by sirvon** [comment]
In the analyticService create a no return method called mixpanelFlush()
and call it in onDestroy like so...

```java
    @Override
    public void onDestroy() {
        Log.v(TAG+"_LIFECYCLE","OnDestroy");
        super.onDestroy();
        analyticService.mixpanel_flush();

    }
```

**Comment by JoanZapata** [comment]
If everything you do in with your mixpanel instance doesn't need to be asynchronous, then don't use asyncservice. Otherwise, put everything you need to do with your mixpanel instance in your analytics service and only use the service from your activity / fragment. The service is the only thing guaranteed to be present at anytime.

By the way this question is not related to asyncservice, you would have the same problem using any other thread management structure like `AsyncTask`.
