### ISSUE TITLE
What's the difference between return and send? Why return at all?

### ISSUE THREAD

**Issue by m4hmoud** [JoanZapata/android-asyncservice#3]
I was checking out your library and I find it a little confusing:

Why do service methods return something? And what's the difference between sending a message and returning that same message? 

As asynchronous calls, having return makes little sense to me. What's the logic behind it?

**Comment by JoanZapata** [comment]
You're right, technically it's exactly the same, but I think both should exist.

```return``` feels more "natural" when you look at the service, the method signature speaks for itself.
It also make the service easier to test in a synchronous way, by instantiating it manually.

```send()``` is supposed to be used only if you can't do otherwise. For example, if you make an asynchronous call **inside** the service method, you would use ```send()``` in the callback.
